arb-dir: lib/l10n
template-arb-file: app_en.arb

# 改這裡：產出的 .dart 放在 lib/l10n
output-dir: lib/l10n

output-class: AppLocalizations
output-localization-file: app_localizations.dart

use-deferred-loading: false

preferred-supported-locales:
  - en
  - zh_TW
  - ja
  - ko
  - de
