// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtlDTKA8tziBfQ1xCNtBw40HqtCByra_8',
    appId: '1:766149685714:web:0f36c50937237e5c83580b',
    messagingSenderId: '766149685714',
    projectId: 'pop-card-bf635',
    authDomain: 'pop-card-bf635.firebaseapp.com',
    storageBucket: 'pop-card-bf635.firebasestorage.app',
    measurementId: 'G-GRWDCQZMY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC50Y2VGwJpocL4RW6JLhLBrPcJbPajv6s',
    appId: '1:766149685714:android:3400c76587e1345d83580b',
    messagingSenderId: '766149685714',
    projectId: 'pop-card-bf635',
    storageBucket: 'pop-card-bf635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8mi1ypHdRQM6h6z0YkRPKDtvi0K__ng',
    appId: '1:766149685714:ios:2145ad0c439f9f6e83580b',
    messagingSenderId: '766149685714',
    projectId: 'pop-card-bf635',
    storageBucket: 'pop-card-bf635.firebasestorage.app',
    androidClientId:
        '766149685714-grt1cl6pvkqbrb3pc2896c98kv76u9j7.apps.googleusercontent.com',
    iosClientId:
        '766149685714-jvpc78c82du92a73bl3rqq5g4euah4nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8mi1ypHdRQM6h6z0YkRPKDtvi0K__ng',
    appId: '1:766149685714:ios:2145ad0c439f9f6e83580b',
    messagingSenderId: '766149685714',
    projectId: 'pop-card-bf635',
    storageBucket: 'pop-card-bf635.firebasestorage.app',
    androidClientId:
        '766149685714-grt1cl6pvkqbrb3pc2896c98kv76u9j7.apps.googleusercontent.com',
    iosClientId:
        '766149685714-jvpc78c82du92a73bl3rqq5g4euah4nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtlDTKA8tziBfQ1xCNtBw40HqtCByra_8',
    appId: '1:766149685714:web:79186d93da21e60c83580b',
    messagingSenderId: '766149685714',
    projectId: 'pop-card-bf635',
    authDomain: 'pop-card-bf635.firebaseapp.com',
    storageBucket: 'pop-card-bf635.firebasestorage.app',
    measurementId: 'G-VGF6WXJ24D',
  );
}
